# Generated by Django 5.2.3 on 2025-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='scenario',
            field=models.TextField(default=''),
        ),
    ]
